cayanmeisterbetrieb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'frontend.views.error_404'

frontend/urls.py
from django.urls import path
from . import views

app_name='frontend'
urlpatterns = [
    path('leistung/', views.leistung, name='leistung'),
    path('kontakt/', views.kontakt, name='contact'),
    path('aboutus/', views.aboutus, name='aboutus'),

    #law stuff
    path('impressum/', views.impressum, name='impressum'),
    path('datenschutz/', views.datenschutz, name='datenschutz'),
    path('agb/', views.agb, name='agb'),



    path('', views.home, name='home')
]

frontend/models.py
from django.db import models


class Contact(models.Model):
    SCHADEN_MELDEN = 0
    PROBLEM_MELDEN = 1
    KOSTEN_ANFRAGE = 2
    KARIERRE = 3
    SONSTIGES = 4
   
    topics = (
        (SCHADEN_MELDEN, 'Schaden am Auto'),
        (PROBLEM_MELDEN, 'Problem am Auto'),
        (KOSTEN_ANFRAGE, 'Kostenanfrage'),
        (KARIERRE, 'Karriere'),
        (SONSTIGES, 'Sonstiges'),
    )

    topic = models.IntegerField(
        default=0, choices=topics, verbose_name='Anliegen')
    firstname = models.CharField(max_length=100, verbose_name='Vorname*')
    lastname = models.CharField(max_length=100, verbose_name='Nachname*')
    email = models.EmailField(verbose_name='Email*')
    tel = models.CharField(max_length=26, null=True,
                           blank=True, verbose_name='Telefonnummer*')
    message = models.TextField(verbose_name='Nachricht')
    inquiry_send_at_date = models.DateTimeField(
        auto_now_add=True, verbose_name='Datum')
    checked = models.BooleanField(default=False, verbose_name='Bearbeitet?')

    def __str__():
        return f'{self.firstname}s contact'

frontend/forms.py
# we will add tippgeber as "contact-reason" in the regular contactform.
# the Reasons in contactform: "Tippgeber",


from django.forms import ModelForm, forms
from captcha.fields import ReCaptchaField

from .models import *


# this is the GOOGLE RECAPTCHA Form !


class ContactForm(ModelForm):
    #captcha = ReCaptchaField()

    class Meta:
        model = Contact
        fields = ['topic', 'firstname', 'lastname', 'email',
                  'tel', 'message']

frontend/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.core.mail import EmailMultiAlternatives, BadHeaderError, EmailMessage, send_mail
from django.views.decorators.http import require_POST
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings


def send_contact_mail(whichform, firstname, lastname, email, customerMessage, tel,topic):
    # we enter the data that the form includes
    context = {
        'whichform': whichform,
        'firstname': firstname,
        'lastname': lastname,
        'email': email,
        'message': customerMessage,
        'tel': tel,
        'topic': topic,
    }

    subject = "Ein Kunde hat geschrieben! Cayan Meisterbetrieb Website."
    message = render_to_string(
        "frontend/mail.html", context
    )
    # print(message)
    striped_message = strip_tags(message)
    #print("we are here 2")
    # HERE IS THE PROBLEM
    msg = EmailMultiAlternatives(subject, striped_message,
                                 from_email=settings.SERVER_EMAIL, to=[settings.CAYAN_MAIL])
    msg.attach_alternative(message, "text/html")
    # if m == 1, than the message has been successfully sended
    m = msg.send(fail_silently=True)
    print('message is ', m)

def anfrageerhalten(request):
    context={}
    return render(request, 'frontend/anfrageerhalten.html', context)

def home(request):
    context = {}
    return render(request, 'frontend/home.html', context)

def aboutus(request):
    context = {}
    return render(request, 'frontend/aboutus.html', context)

def kontakt(request):
    context = {}
    if request.method == 'POST':
        contactform = ContactForm(request.POST)
        if contactform.is_valid():
            #captcha = contactform.get('captcha')
            # request.POST.get('recaptcha_form')
            """

                    if not captcha:
                recaptcha_form = FormWithCaptcha()
                form = ContactForm()
                print("recaptcha error")
                print(captcha)
                context['form'] = form
                context['recaptcha_form'] = recaptcha_form
                context['error_captcha'] = "Du musst den Recaptcha Test bestehen"
                return render(request, 'pages/contact.html', context)
            
            
            """

            c = contactform.save()

            send_contact_mail(
                'Kontaktformular', request.POST['firstname'], request.POST['lastname'], request.POST['email'], request.POST['message'], request.POST['tel'],request.POST['topic'])
            form = ContactForm()
            context['form']=form
            context['success']='Erfolgreich abgesendet'
            return render(request, 'frontend/kontakt.html', context)
            # now send a mail to tumuratas, so that he can notice that there has arrived a mai
        else:
            context['form'] = ContactForm(
                initial={
                    'topic': request.POST['topic'],
                    'firstname': request.POST['firstname'],
                    'lastname': request.POST['lastname'],
                    'email': request.POST['email'],
                    'tel': request.POST['tel'],
                    'street': request.POST['street'],
                    'postialcode': request.POST['postialcode'],
                    'city': request.POST['city'],
                    'message': request.POST['message'],

                }
            )
            context['errors'] = "Moment. Es gab einen Fehler."
            return render(request, 'frontend/kontakt.html', context)
    else:
        #recaptcha_form = FormWithCaptcha()
        form = ContactForm()
        context['form'] = form
        #context['recaptcha_form'] = recaptcha_form
    return render(request, 'frontend/kontakt.html', context)

def leistung(request):
    context = {}
    return render(request, 'frontend/leistung.html', context)


def impressum(request):
    context = {}
    return render(request, 'frontend/impressum.html', context)

def datenschutz(request):
    context = {}
    return render(request, 'frontend/datasecurity.html', context)

def agb(request):
    context = {}
    return render(request, 'frontend/agb.html', context)

def error_404(request, exception):
    context = {}
    return render(request, 'frontend/404.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/footer.css' %}"/>
    <link rel="icon" type="image/gif/png" href="{% static 'img/cayanlogo.png'%}">



    <link href="https://fonts.googleapis.com/css2?family=Courgette&family=Poppins:wght@300;400;500;600;700;800&family=Water+Brush&display=swap" rel="stylesheet">
    <title>
      {% block title %}
      {% endblock title %}
    </title>
    <link
      href="https://fonts.googleapis.com/css?family=Poppins:300,900&display=swap"
      rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>

    {% block cssfiles %}

    {% endblock cssfiles %}
  </head>
  <body>
    <div class="fullcont">

    {% include 'includes/nav.html' %}
    <main>
      <div class="contentbox">
      {% block content %}

      {% endblock content %}
      </div>

    </main>
    {% include 'includes/footer.html' %}

    
  </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.0/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.0/ScrollTrigger.min.js"></script>
    {% block jsfiles %}
    {% endblock jsfiles %}
  </body>
</html>

templates/frontend/datasecurity.html
{% extends 'base.html' %}
{% load static %}
{% block cssfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/impressum.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/story.css' %}">

{% endblock cssfiles %}
{% block title%}CAYAN MEISTERBETRIEB - Datenschutz{% endblock title%}
{% block content %}
<div class="im-big-cont">
    <div class="im-cont">
            <div class="im-boxa">
                <div class="imh1">Datenschutz</div>
                <div class="impp2">Im folgenden möchten wir Sie darüber aufklären wie wir Ihre personbezogenen Daten verarbeiten, 
                hier folgend als "Daten" bezeichnet. Diese Datenschutzerklärung gilt für jede Applikation, Softwareprodukt sowie bei Social Media 
                Plattformen wie Instagram und Facebook. Die verwendeten Begriffe sind nicht gesetzesspezifisch.</div>
               
            </div>
            <div class="imbox im-boxb">
                <div class="imtext">
                    <div class="imub">Sicherheitsmaßnahmen</div>
                    <div class="flex-row">
                        <div class="impp">Wir setzen bei dem Schutz Ihrer Daten stets auf den neusten Stand der Technik. Der Datentransfer findet mit SSH Verschlüsselung
                        statt. Sie erkennen SSH Verbindung an dem 'https://' in der URL-leiste Ihres Browsers. Außerdem sind Passwörter verschlüsselt gespeichert in der Datenbank.
                        </div>
                    </div>
                </div>
            </div>
            <div class="imbox im-boxc">
                <div class="imtext">
                    <div class="imub">Löschung von Daten</div>
                    <div class="impp">Ihre Accountdaten werden 1 Jahr nach der Löschung des Accounts gelöscht. Sollten Sie eine sofortige Löschung wünschen teilen Sie uns dies
                    bitte mit. Anonsten werden Daten per Session auf Ihrem Browser gespeichert, damit Sie einen Bestellvorgang pausieren und später fortsetzen können. 
                    Beim schließen des Browsers oder löschen des Cache sollten auch diese Daten gelöscht werden. Achtung, wir haben momentan die Möglichkeit Accounts zu erstellen deactiviert. Somit ist dieser Absatz obsolete bis das Accountsystem wieder online ist. Die Regelungen sind noch anwendbar bei ihrer Kontaktmitteilung. Diese wird geschützt in unserer verschlüsselten Datenbank und nach Handhabung ihrer Anfrage im laufe von 1 Jahr gelöscht.</div>
                </div>
            </div>
            <div class="imbox im-boxd">
                <div class="imtext">
                    <div class="imub">Einwilligung (Art. 6 Abs. 1 S. 1 lit. a. DSGVO) </div>
                    <div class="impp">Die betroffene Person hat ihre Einwilligung in die Verarbeitung der sie betreffenden personenbezogenen Daten 
                    für einen spezifischen Zweck oder mehrere bestimmte Zwecke gegeben.</div>
                </div>
            </div>
            <div class="imbox im-boxe">
                <div class="imtext">
                    <div class="imub">Zugriff auf Daten</div>
                    <div class="impp">Mitarbeiter von Racine Deux haben Zugriff auf Ihre Daten, wenn Wartungsarbeiten an der Website vorgenommen werden. Passwörter sind verschlüsselt gespeichert, sodass keiner außer Ihnen selbst
                    diese Art von Daten lesen kann. Achtung: Wir verwenden keine Cookies oder Sessions in dieser Website.</div>
                </div>
            </div>
    </div>
    <div class="ubbox">
        <div class="ubbox-ub">Erklärung zur sofortigen Löschung Ihrer Daten.</div>
        <div class="ubb-txt">Sie haben das Recht jederzeit Ihre Daten löschen zu lassen.
            Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag an dem Sie oder ein von Ihnen benannter Dritter, der nicht der Beförderer ist, die Waren in Besitz genommen haben bzw. hat.<br><br>
            Um Ihr Widerrufsrecht auszuüben, müssen Sie uns per EMail an ctmeisterbetrieb@gmail.com mittels einer eindeutigen Erklärung über Ihren Entschluss ihre Daten löschen zu lassen, informieren. Wichtig ist, dass Ihr Widerruf innerhalb der 14 tägigen Widerrufsfrist bei uns ankommt. 
            
        </div>

    </div>

</div>

{% endblock content %}

templates/frontend/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CAYAN - KFZ MEISTERBETRIEB{% endblock title %}
{% block cssfiles %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>

{% endblock cssfiles %}


{% block content %}
    <div class="home-intro" id="homeintro" style="background-image:url({% static 'img/titlepic.jpeg'%})">
      <div class="innerfilter">
        <h3>KFZ-Meisterbetrieb Cayan</h3>
        <h1 id="h211">Lieber vorsorgen, als im Nachhinein bereuen.</h1>
        <a href="{% url 'frontend:contact'%}" class="standardbutton">Jetzt kontaktieren ></a>

      </div>
    </div>
   
    <div class="home-about-container">
        <div class="home-about">
            <h2>Qualität und optimaler Service.</h2>
            <div class="columns2">
                <div class="col2 fade" id="d282">
                <h3>Keine versteckten Kosten.</h3>
                <p>
                    Bei uns wissen Sie von anfang an, was Sie für Ihr Geld bekommen. Wir legen größten Wert auf Transparenz und gute Kommunikation mit unseren Kunden
                </p>
                </div>
                <div class="col3 fade" id="d28w2">
                <h3>Der Meisterbetrieb in Mörfelden-Walldorf.</h3>
                <p>
                    Kommen Sie vorbei und lernen unseren Betrieb besser kennen. Wir freuen uns auf Sie.
                </p>
                </div>
                <div class="col4 fade" id="dwqqq82">
                <h3>Ausgezeichneter Service.</h3>
                <p>Unser Personal ist in höchstem Maße darauf ausgebildet die Ursache für technische Probleme zu erkennen und zu beheben. Das Auto ist für uns mehr als ein Fahrzeug. Es ist unsere Leidenschaft und unser Handwerk.
                    
                </p>
                </div>
                <div class="col5 pic"></div>
            </div>
        </div>
    </div>


    <div class="home-gal">
      <div class="home-gal-grid">
        <div class="homga homeg txthome">
          <h2>Aus liebe zum Auto.</h2>
          <p>Moderne Automobile sind hochkomplizierte Computer. Unser Personal ist geschult auch mit fortgeschrittenster Technologie umgehen zu können um Ihnen einen Rundum Service zu bieten.</p>
        </div>
        <div class="homgb homeg" style="background-image:url({% static 'img/c3.jpg'%})"></div>
        <div class="homgc homeg" style="background-image:url({% static 'img/mercedes.jpg'%})"></div>
        <div class="homgd homeg txthome">
          <h2>Pflege und Wartung.</h2>
          <p>
            Regelmößige Pflege für Ihr Auto ist unerlässlich. Wir kümmern uns gerne darum. Kontaktieren Sie uns jetzt und vereinbaren Sie einen Termin.
          </p>
        </div>
        <div class="homge homeg txthome">
          <h2>Top Konditionen.</h2>
          <p>
            Bei uns erwarten Sie transparente Preise. Kommen Sie vorbei oder kontaktieren Sie uns jetzt für mehr Informationen.
          </p>
        </div>
        <div class="homgf homeg"  id="picend" style="background-image:url({% static 'img/c12.jpg'%})"></div>
      </div>
    </div>

    <div class="leistungsbox">
      <div class="innerleistungsbox">
        <div class="l1">
          <h1>Unsere Leistung</h1>
        </div>
        <div class="l2">
          <div class="litem lia">
            <div class="liicon" style="background-image:url({% static 'img/kfzreparaturicon.png'%})"></div>
            <div class="litxt">KFZ. Reparatur</div>
          </div>
          <div class="litem lib">
            <div class="liicon" style="background-image:url({% static 'img/motorservice.png'%})"></div>
            <div class="litxt">Motorservice</div>
          </div>
          <div class="litem lic">
            <div class="liicon" style="background-image:url({% static 'img/reifenicon.png'%})"></div>
            <div class="litxt">Reifenwechsel</div>
          </div>
          <div class="litem lid">
            <div class="liicon" style="background-image:url({% static 'img/lackieren.png'%})"></div>
            <div class="litxt">Lackierung</div>
          </div>
        </div>
        <div class="l3">
          <a href="{% url 'frontend:leistung'%}" class="standardbutton">Mehr erfahren ></a>
        </div>


      </div>
    </div>

    

  <script src="{% static 'js/observer.js' %}"></script>
{% endblock content %}
{% block jsfiles %}
<script>

  let currentScrollPosition = 0;
  let scrollAmount = 420;

  const sCont = document.querySelector(".story-container");
  const hScroll = document.querySelector(".horizontal-scroll");

  const btnScrollLeft = document.querySelector("#btn-scroll-left");
  const btnScrollRight = document.querySelector("#btn-scroll-right");

  btnScrollLeft.style.opacity = "0";


  let maxScroll = -sCont.offsetWidth + hScroll.offsetWidth;

  function scrollHorizontally(val){
      currentScrollPosition += (val * scrollAmount);
      if(currentScrollPosition > 0 ){
          currentScrollPosition = 0
          btnScrollLeft.style.opacity = "0";

      }else{
          btnScrollLeft.style.opacity="1";
      }
      if(currentScrollPosition < maxScroll){
          currentScrollPosition = maxScroll;
          btnScrollRight.style.opacity = "0";

      }else{
          btnScrollRight.style.opacity = "1";


      }
      sCont.style.left = currentScrollPosition + "px";
  }

</script>
  <script>
      gsap.registerPlugin(ScrollTrigger);
      ScrollTrigger.defaults({
      toggleActions: "restart none none none",
      });   
  
      // This is the YumaBag Text here
      gsap.from("#h211", {
          scrollTrigger: "#homeintro",
          toggleActions: "restart none none none",
          duration: 1.2,
          x: 220,
          opacity:0,
          ease:"ease.in"
      });

      gsap.from("#d282", {
        scrollTrigger: "#columns2",
        toggleActions: "restart none none none",
        duration: 0.8,
        x: 420,
        opacity:0,
        ease:"ease.in"
    });

    gsap.from("#d28w2", {
      scrollTrigger: "#columns2",
      toggleActions: "restart none none none",
      duration: 1.2,
      x: 220,
      opacity:0,
      ease:"ease.in"
  });

  gsap.from("#dwqqq82", {
    scrollTrigger: "#columns2",
    toggleActions: "restart none none none",
    duration: 0.92,
    x: -220,
    opacity:0,
    ease:"ease.in"
});

//picture block
gsap.from(".homga", {
  scrollTrigger: ".homga",
  toggleActions: "restart none none none",
  duration: 0.92,
  x: -220,
  opacity:0,
  ease:"ease.in"
});
gsap.from(".homgb", {
  scrollTrigger: ".homgb",
  toggleActions: "restart none none none",
  duration: 0.52,
  x: 320,
  opacity:0,
  ease:"ease.in"
});
gsap.from(".homgc", {
  scrollTrigger: ".homgc",
  toggleActions: "restart none none none",
  duration: 0.72,
  x: -420,
  opacity:0,
  ease:"ease.in"
});


gsap.from(".homgd", {
  scrollTrigger: ".homgd",
  toggleActions: "restart none none none",
  duration: 0.72,
  x: 420,
  opacity:0,
  ease:"ease.in"
});
gsap.from(".homge", {
  scrollTrigger: ".homge",
  toggleActions: "restart none none none",
  duration: 1.1,
  x: -320,
  opacity:0,
  ease:"ease.in"
});

gsap.from(".homgf", {
  scrollTrigger: ".homgf",
  toggleActions: "restart none none none",
  duration: 0.8,
  delay:1,
  x: 320,
  opacity:0,
  ease:"ease.in"
});


gsap.from(".hgb", {
  scrollTrigger: ".hgb",
  toggleActions: "restart none none none",
  duration: 0.6,
  delay:1,
  x: 420,
  opacity:0,
  ease:"ease.in"
});
gsap.from(".hgc", {
  scrollTrigger: ".hgc",
  toggleActions: "restart none none none",
  duration: 0.7,
  delay:1,
  x: -320,
  opacity:0,
  ease:"ease.in"
});
gsap.from(".hgd", {
  scrollTrigger: ".hgd",
  toggleActions: "restart none none none",
  duration: 0.8,
  delay:1,
  x: -320,
  opacity:0,
  ease:"ease.in"
});

gsap.from(".hge", {
  scrollTrigger: ".hge",
  toggleActions: "restart none none none",
  duration: 0.8,
  delay:1,
  x: 320,
  opacity:0,
  ease:"ease.in"
});

  </script>
{% endblock jsfiles %}

templates/frontend/kontakt.html
{% extends 'base.html' %}
{% load static %}
{% block title %}KONTAKT - CAYAN{% endblock title %}
{% block cssfiles %}
    <link rel="stylesheet" href="{% static 'css/kontakt.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>

{% endblock cssfiles %}
{% block content %}
<div style="width:100%; height:100px;background-color:black"></div>
<div class="backgroundpic">
<div class="titlepiccon" style="padding-top:100px; background-image:url({% static 'img/c2.jpg'%}); ">
    <div class="innerfilter"></div>
</div>
</div>
<div class="todocontact">
    <div class="contactdiv">
        <h1>Kontakt</h1>
        {% if success %}
        <div class="cooldiv success-div">
            <h4>{{success}}</h4>
        </div>
    {% endif %}
    {% if error %}
        <div class="cooldiv error-div">
            <h4>{{error}}</h4>
        </div>
    {% endif %}
    <form id="contactform" method="post" action="{% url 'frontend:contact' %}">
        {% csrf_token %}
        <div class="contact-flexcont">
            {% for field in form  %}
            <div class="inputdiv">
                <div class="superlabel">
                    {{field.label}}
                </div>
                {{field}}
                
            </div>
            {% endfor %}
        </div>
        
        <div class="flexcenter">
            <input type="submit" id="sendbtn" value="Sende Nachricht">
        </div>
    </form>
    <div>
<div>
   

{% endblock content %}
{% block jsfiles %}
{% endblock jsfiles %}

templates/includes/footer.html
{% load static %}

<div class="footercont">
    <div class="footergrid">
        
        <div class="fg2" style="background-image:url({% static 'img/cayanlogo.png'%})">
            
        </div>
        <div class="fg3">
            <a href="{% url 'frontend:impressum'%}">Impressum</a>
            <a href="{% url 'frontend:datenschutz'%}">Datenschutz</a>
        </div>
        <div class="fg4">
            <a href="#"><div class="socialicon" style="background-image:url({% static 'img/facebook.png'%})"></div></a>
            <a href="#"><div class="socialicon" style="background-image:url({% static 'img/instagram.png'%})"></div></a>
            <a href="#">
                <div class="teliconfield">
                    <div class="telicon" style="background-image:url({% static 'img/phone.png'%});margin-right:5px;"></div>
                    <div class="number">06105 7038233</div>
                </div>
            </a>
        </div>
    </div>
    <div class="fg5">
        2022 CAYAN MEISTERBETRIEB. Powered by Racine Deux.

    </div>



</div>

templates/includes/nav.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      href="https://fonts.googleapis.com/css?family=Poppins:300,900&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/nav.css'%}"/>
  </head>
  <body>
    <header id="header">
      <a href="{% url 'frontend:home' %}" class="site-logo" aria-label="homepage">
        <div class="pichead">
          <div class="logo" id="logopic" style="background-image:url({% static 'img/cayanlogo.png'%})"></div>
          <div class="companyname">
            <h3>KFZ.-Meisterbetrieb Cayan</h3>
            <h6>Nur das beste für Mörfelden-Walldorf</h6>
          </div>
        </div>
      </a>
      <nav class="main-nav" id="mainnav">
        <ul class="nav__list">
          <li class="nav__list-item"><a href="{% url 'frontend:home'%}" class="nav__link desktoplink">Home</a></li>
          <li class="nav__list-item">
            <a href="{% url 'frontend:leistung'%}" class="nav__link desktoplink">Leistung</a>
          </li>
          <li class="nav__list-item">
            <a href="{% url 'frontend:contact'%}" class="nav__link desktoplink">Kontakt</a>
          </li>
          
          <!--
            <li class="nav__list-item">
            <a href="{% url 'frontend:home'%}" class="nav__link desktoplink"></a>
          </li>
          <li class="nav__list-item">
            <a href="{% url 'frontend:home' %}" class="nav__link desktoplink">About us</a>
          </li>
          <li class="nav__list-item"><a href="{% url 'frontend:home' %}" class="nav__link desktoplink">Gatronomie</a></li>

          -->
          


        </ul>
      </nav>
      <nav class="account">
        <div class="menu-btn whited" id="respsym">
          <div class="menu-btn-burger">
        </div>
      </nav>     
    </header>
    <div class="respheader responsiv-nav-container closed" id="responsiv-nav-container">
      <div class="respitem"><a href="{% url 'frontend:home'%}">Home</a></div>
      <div class="respitem"><a href="{% url 'frontend:leistung'%}">Leistung</a></div>
      
      <div class="respitem"><a href="{% url 'frontend:contact'%}">Kontakt</a></div>
    </div>
   
    <script>
      // logo and navigation bar
      // the whole navbar
      const nav = document.getElementById("header");
      // the responsiv icon 
      const responsivIcon = document.getElementById("respsym");
      const logo = document.getElementById("logopic");
      console.log("responsivIcon", responsivIcon);
      const menuBtn = document.querySelector('.menu-btn');
  
  
      const menuSite = document.getElementById('responsiv-nav-container');
  
      let respNavSite = document.querySelector('.activateresp');
      let menuOpen = false;
  
      menuBtn.addEventListener('click', () => {
          if (!menuOpen) {
              menuBtn.classList.add('open');
              responsivIcon.classList.add("transparented");
              nav.classList.add("transparented");
              responsivIcon.classList.remove("whited");
              header.classList.add("blacked");

              menuOpen = true;
              console.log(menuOpen)
  
              menuSite.classList.add('resp-open');
  
              setTimeout(function (){
                  menuSite.style.width = "100%";
              }, 0.5);
  
  
              logo.style.display = "none"
          } else {
              menuBtn.classList.remove('open');
              menuOpen = false;
              menuSite.classList.remove('resp-open');
              menuSite.style.width = "0";
              logo.style.display = "block";
              responsivIcon.classList.remove("transparented");
              header.classList.remove("blacked");


              nav.classList.remove("transparented");
              responsivIcon.classList.add("whited");
          }
      });
  </script>
   
  </body>
</html>